name: Generate test coverage xml report.
on: [push]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Generate test coverage xml report
        run: 
          dotnet test --collect:"XPlat Code Coverage"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: /home/runner/work/customer-class-library/customer-class-library/**/TestResults/**/coverage.cobertura.xml
          flags: unittests
          fail_ci_if_error: true
