name: Generate test coverage xml report.
on:
  push:
    branches:
      - main
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Generate test coverage xml report
        run: 
          dotnet test --collect:"XPlat Code Coverage"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: /home/runner/work/customer-class-library/customer-class-library/**/TestResults/**/coverage.cobertura.xml
